Login Functionality
LTT-Gatech/CarCareAndroid pull request #41
Opened 2017-02-18 19:03 UTC by anoll3

Added basic login functionality to the app through Google Sign In.

2017-02-18 19:51 UTC, asasine requested changes
Mostly concerns over security

2017-02-18 19:51 UTC, asasine commented on app/build.gradle
>          minSdkVersion 18
This needs to be `minSdkVersion 15` so I can develop on my phone.

2017-02-18 19:51 UTC, asasine commented on app/google-services.json
> +{
The information in this file doesn't belong on a remote repo. They are considered secrets and shouldn't be made publicly available.

2017-02-18 19:51 UTC, asasine commented on app/src/main/java/com/teamltt/carcare/database/DbHelper.java
> +        return cursor != null;
Does this work?

2017-02-18 19:51 UTC, asasine commented on app/src/main/java/com/teamltt/carcare/activity/HomeActivity.java
> +        String userId = intent.getStringExtra(LoginActivity.EXTRA_MESSAGE + ".USERID");
See my message in LoginActivity about making individual strings for each key

2017-02-18 19:51 UTC, asasine commented on app/src/main/java/com/teamltt/carcare/activity/LoginActivity.java
> +            intent.putExtra(EXTRA_MESSAGE + ".USERID", google_id);
Instead of `EXTRA_MESSAGE + ".FIRSTNAME"`, why not make individual static strings for each argument key?

2017-02-18 19:51 UTC, asasine commented on app/src/main/java/com/teamltt/carcare/database/contract/UserContract.java
> +        String where_cond = "UserEntry.COLUMN_GOOGLE_USER_ID = " + google_user_id;
Don't hardcode the key, instead change this to `String where_cond = UserEntry.COLUMN_NAME_GOOGLE_USER_ID + " = ?";`, then make a `String[] args = {google_user_id};`, and pass it in as an argument after the `where_cond`

2017-02-18 19:56 UTC, asasine commented on app/google-services.json
> +{
This information also needs to be scrubbed from the repo.

2017-02-18 20:25 UTC, asasine commented on app/google-services.json
> +{
This file should also be added to the .gitignore; we can distribute it locally at the next meeting.

2017-02-18 20:43 UTC, asasine requested changes
Style changes and code semantics

2017-02-18 20:43 UTC, asasine commented on app/src/main/java/com/teamltt/carcare/activity/LoginActivity.java
> +    protected void onResume() {
Should this be placed in `onStart` since it's disconnected in `onStop`?

2017-02-18 20:43 UTC, asasine commented on app/src/main/java/com/teamltt/carcare/activity/LoginActivity.java
> +        if (google_api_client.isConnected()) {
Should this be `!google_api_client.isConnected()`?

2017-02-18 20:43 UTC, asasine commented on app/src/main/java/com/teamltt/carcare/activity/LoginActivity.java
> +    ProgressDialog progress_dialog;
camelCase please

2017-02-18 20:43 UTC, asasine commented on app/src/main/java/com/teamltt/carcare/activity/LoginActivity.java
> +    GoogleApiClient google_api_client;
camelCase please

2017-02-18 20:59 UTC, anoll3 commented on app/src/main/java/com/teamltt/carcare/activity/LoginActivity.java
> +    protected void onResume() {
I don't follow. What exactly are you suggesting? For onResume() to be moved?

2017-02-18 21:21 UTC, asasine requested changes

2017-02-18 21:21 UTC, asasine commented on .gitignore
> +/google-services.json
change to just `google-services.json` or specify `app/google-services.json`

2017-02-18 21:21 UTC, asasine commented on app/src/main/java/com/teamltt/carcare/activity/LoginActivity.java
> +    protected void onResume() {
To change this override method from `onResume` to `onStart`. If you look at the Android activity lifecycle docs [here](https://developer.android.com/guide/components/activities/activity-lifecycle.html#alc) you can see how `onStop` and `onStart` are connected whereas `onPause` and `onResume` are connected. If we are disconnecting the the googleApiClient in `onStop`, shouldn't we be [re]connecting in `onStart`?

2017-02-18 21:26 UTC, anoll3 commented on app/src/main/java/com/teamltt/carcare/activity/LoginActivity.java
> +    protected void onResume() {
Maybe I'm misunderstanding, but I have `onStart()` implemented already and based on the life cycle chart `onStart()` goes through `onResume()`. I can move the connection to onStart() if that's what you mean.

2017-02-18 21:29 UTC, anoll3 commented on app/src/main/java/com/teamltt/carcare/database/DbHelper.java
> +        return cursor != null;
I believe so. The cursor should be null if no user with the given id is found. If you can tell me how to check the database I'll make sure it's not duplicated.

2017-02-18 21:40 UTC, asasine commented on app/src/main/java/com/teamltt/carcare/activity/LoginActivity.java
> +    protected void onResume() {
If the user navigates away from the app to the home screen, the activity is stopped and the client is disconnected. When they navigate back, a login is attempted in `onStart` with a disconnected client. Before we attempt a login, we should ensure that the client is connected, or connect if it isn't.

2017-02-19 16:26 UTC, asasine commented
This closes #5, closes #6

2017-02-19 16:28 UTC, merged